### ISSUE TITLE
double free detected in tcache 2

### ISSUE THREAD

**Issue by yeyueluke** [CrowCpp/Crow#686]
use example_chat demo when send anything from web,it crashes with message : double free detected in tcache 2
full crash messages as follow:
(2023-07-11 07:59:21) [INFO    ] Crow/master server is running at http://0.0.0.0:40080 using 2 threads
(2023-07-11 07:59:21) [INFO    ] Call `app.loglevel(crow::LogLevel::Warning)` to hide Info level logs.
(2023-07-11 07:59:30) [INFO    ] Request: 127.0.0.1:34364 0x5568e02afef0 HTTP/1.1 GET /
(2023-07-11 07:59:30) [INFO    ] Response: 0x5568e02afef0 / 200 0
(2023-07-11 07:59:30) [INFO    ] Request: 127.0.0.1:34364 0x5568e02afef0 HTTP/1.1 GET /logs
(2023-07-11 07:59:30) [INFO    ] logs requested
(2023-07-11 07:59:30) [INFO    ] logs completed
(2023-07-11 07:59:30) [INFO    ] Response: 0x5568e02afef0 /logs 200 0
(2023-07-11 07:59:30) [INFO    ] Request: 127.0.0.1:34364 0x5568e02afef0 HTTP/1.1 GET /logs/0
(2023-07-11 07:59:30) [INFO    ] logs with last 0
(2023-07-11 07:59:32) [INFO    ] Response: 0x7fbf50000c20 /favicon.ico 404 0
(2023-07-11 07:59:35) [INFO    ] Request: 127.0.0.1:42838 0x7fbf50002190 HTTP/1.1 POST /send
(2023-07-11 07:59:35) [INFO    ] msg from client: 123
(2023-07-11 07:59:35) [INFO    ] Response: 0x5568e02afef0 /logs/0 200 0
free(): double free detected in tcache 2
已放弃 (核心已转储)

**Comment by gittiver** [comment]
are you using the release or git:master version of crow?

**Comment by gittiver** [comment]
as we got no answer I will close this issue.

**Comment by TheQue42** [comment]
I just updated to v1.1.0 (from 1.0+5), and started getting these as well. Started testing in master first, with the same results, and then in v.1.1.0.

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff7294a73 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7241176 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7228917 in __GI_abort () at abort.c:79
#4  0x00007ffff72297e8 in __libc_message_impl (fmt=fmt@entry=0x7ffff73b3321 "%s\n") at ../sysdeps/posix/libc_fatal.c:132
#5  0x00007ffff729f3c7 in malloc_printerr (str=str@entry=0x7ffff73b6660 "free(): double free detected in tcache 2") at malloc.c:5772
#6  0x00007ffff72a19c9 in _int_free (av=0x7fffd0000030, p=<optimized out>, have_lock=have_lock@entry=0) at malloc.c:4541
#7  0x00007ffff72a4143 in __GI___libc_free (mem=<optimized out>) at malloc.c:3398
#8  0x000000000066da1d in std::_Function_base::_Base_manager<crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}>::_M_destroy(std::_Any_data&, std::integral_constant<bool, false>) (__victim=...) at /usr/include/c++/12/bits/std_function.h:175
#9  0x0000000000673778 in std::_Function_base::_Base_manager<crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) (__dest=..., __source=..., __op=<optimized out>)
    at /usr/include/c++/12/bits/std_function.h:203
#10 0x0000000000673815 in std::_Function_handler<void (), crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) (__dest=..., __source=..., __op=<optimized out>)
    at /usr/include/c++/12/bits/std_function.h:282
#11 0x000000000065dd25 in std::function<void ()>::operator=(decltype(nullptr)) (this=this@entry=0x7fff4c008938) at /usr/include/c++/12/bits/std_function.h:505
#12 0x0000000000679568 in crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::prepare_buffers (this=this@entry=0x7fff4c0076c0) at 3pp/CrowCpp/include/crow/http_connection.h:274
#13 0x000000000067c867 in crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::complete_request (this=0x7fff4c0076c0) at 3pp/CrowCpp/include/crow/http_connection.h:259
#14 0x000000000067cc79 in crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}::operator()() const (__closure=<optimized out>) at 3pp/CrowCpp/include/crow/http_connection.h:183
#15 std::__invoke_impl<void, crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}&>(std::__invoke_other, crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}&) (__f=...)
    at /usr/include/c++/12/bits/invoke.h:61
#16 std::__invoke_r<void, crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}&>(crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}&) (__fn=...) at /usr/include/c++/12/bits/invoke.h:111
#17 std::_Function_handler<void (), crow::Connection<crow::SocketAdaptor, crow::Crow<crow::CORSHandler>, crow::CORSHandler>::handle()::{lambda()#2}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/12/bits/std_function.h:290
#18 0x0000000000617f96 in std::function<void ()>::operator()() const (this=this@entry=0x7fff4c008938) at /usr/include/c++/12/bits/std_function.h:591
#19 0x000000000061928e in crow::response::end (this=this@entry=0x7fff4c0088d0) at 3pp/CrowCpp/include/crow/http_response.h:250
```
