### ISSUE TITLE
Mutating Middleware context in CROW_CATCHALL_ROUTE causes Segmentation fault

### ISSUE THREAD

**Issue by lbatuska** [CrowCpp/Crow#859]
When I try to modify a value contained in the context struct in a CROW_CATCHALL_ROUTE it causes a segfault but works perfectly with a CROW_ROUTE

A very minimal example to reproduce it:

```
struct TestMW {
  struct context {  // NOLINT(readability-identifier-naming)
    int id{};
    std::string s;
    context() : s("Test") {}
  };

  void before_handle(  // NOLINT(readability-convert-member-functions-to-static)
      crow::request& req,  // NOLINT(misc-unused-parameters)
      crow::response& res,
      context& ctx) {  // NOLINT(misc-unused-parameters)
  }

  void after_handle(  // NOLINT(readability-convert-member-functions-to-static)
      crow::request& req,   // NOLINT(misc-unused-parameters)
      crow::response& res,  // NOLINT(misc-unused-parameters)
      context& ctx          // NOLINT(misc-unused-parameters)
  ) {}
};

int main() {
  crow::App<TestMW> app;
  app.loglevel(crow::LogLevel::Debug);
  CROW_CATCHALL_ROUTE(app)
  ([&](crow::request const& req, crow::response& res) {
    auto& ctx = app.get_context<TestMW>(req);
    ctx.s = "Something else";
    res.write("Test Write");
    res.end();
  });

  app.port(8181).multithreaded().run();
}
````
When I run the following code and try curl-ing on any url on localhost:8181 I get the following on the server side:

```
(2024-07-27 19:19:54) [INFO    ] Crow/master server is running at http://0.0.0.0:8181 using 12 threads
(2024-07-27 19:19:54) [INFO    ] Call app.loglevel(crow::LogLevel::Warning) to hide Info level logs.
(2024-07-27 19:19:54) [DEBUG   ] 0xaac179bbc840 {0} queue length: 1
(2024-07-27 19:19:58) [DEBUG   ] 0xaac179bbc450 {1} queue length: 1
(2024-07-27 19:19:58) [DEBUG   ] 0xaac179bc7960 timer cancelled: 0xff930fdfdfa8 0
(2024-07-27 19:19:58) [DEBUG   ] task_timer cancelled: 0xff930fdfdfa8 0
(2024-07-27 19:19:58) [DEBUG   ] task_timer scheduled: 0xff930fdfdfa8 1
(2024-07-27 19:19:58) [DEBUG   ] 0xaac179bc7960 timer added: 0xff930fdfdfa8 1
Segmentation fault (core dumped)
```

I have tested it on 2 different systems with different architectures ARM64 / aarch64 (Win11 wsl2) and x86_64 (Arch linux) unfortunately with the same result.
I'm using the origin/v1.2.0 tag with it's latest commit.

Thank You in Advance for the help and let me know if I can provide any extra info!

**Comment by LunarWatcher** [comment]
You don't actually need to mutate. Reads also segfault:
```cpp
  CROW_CATCHALL_ROUTE(app)
  ([&](crow::request const& req, crow::response& res) {
    const auto& ctx = app.get_context<TestMW>(req);
    res.write(ctx.s);
    res.end();
  });
```
The backtrace, as expected, points to line 4 (`res.write(ctx.s)`), with
```
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data (this=0x8)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/basic_string.h:228
#1  0x00005555555702c1 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append (this=0x555555628128, 
    __str=<error reading variable: Cannot access memory at address 0x10>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/basic_string.h:1436
#2  0x000055555557171d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+= (this=0x555555628128, 
    __str=<error reading variable: Cannot access memory at address 0x10>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/basic_string.h:1378
#3  0x0000555555571561 in crow::response::write (this=0x555555628120, body_part=<error reading variable: Cannot access memory at address 0x10>)
    at _deps/crowcpp-src/include/crow/http_response.h:233
#4  0x0000555555561ab9 in main::$_0::operator() (this=0x7fffffffc5a0, req=..., res=...) at /home/olivia/build/crow-bug-859/test.cpp:29
```
This is actually undefined behaviour caused by `req.middleware_context` being `nullptr`, and `app.h` [not checking for this](https://github.com/CrowCpp/Crow/blob/aef1471bd8a055afe88fd5e599a033514746811c/include/crow/app.h#L694), and it ends up returning an invalid struct. Anything you do with any returned middleware, read or write, will be invalid and segfault. 

Ubsan output, for context:
```
/home/olivia/build/crow-bug-859/build/_deps/crowcpp-src/include/crow/app.h:694:25: runtime error: reference binding to null pointer of type 'context_t' (aka 'context<TestMW>')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/olivia/build/crow-bug-859/build/_deps/crowcpp-src/include/crow/app.h:694:25 
/home/olivia/build/crow-bug-859/build/_deps/crowcpp-src/include/crow/middleware_context.h:51:34: runtime error: member call on null pointer of type 'crow::detail::context<TestMW> *'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/olivia/build/crow-bug-859/build/_deps/crowcpp-src/include/crow/middleware_context.h:51:34 
/home/olivia/build/crow-bug-859/build/_deps/crowcpp-src/include/crow/middleware_context.h:53:24: runtime error: reference binding to null pointer of type 'typename TestMW::context'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/olivia/build/crow-bug-859/build/_deps/crowcpp-src/include/crow/middleware_context.h:53:24 
/home/olivia/build/crow-bug-859/build/_deps/crowcpp-src/include/crow/app.h:695:33: runtime error: reference binding to null pointer of type 'typename TestMW::context'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/olivia/build/crow-bug-859/build/_deps/crowcpp-src/include/crow/app.h:695:33 
/home/olivia/build/crow-bug-859/test.cpp:28:23: runtime error: reference binding to null pointer of type 'const typename TestMW::context'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/olivia/build/crow-bug-859/test.cpp:28:23 
UndefinedBehaviorSanitizer:DEADLYSIGNAL
```
